name: CMake on a single platform

on:
  push:
    branches: [ "main", "Dev" ]
  pull_request:
    branches: [ "main", "Dev" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      if: always()
      working-directory: ${{github.workspace}}/build
      timeout-minutes: 5
      run: |
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure -V
        exit_code=$?
        if [ $exit_code -eq 0 ]; then
          echo "Tests completed successfully"
        else
          echo "Tests failed with exit code $exit_code"
          exit $exit_code
        fi
