#ifndef COMSHOP_H
#define COMSHOP_H

#include "Commercial.h"

/**
 * @class ComShop
 * @brief Represents a commercial shop building.
 *
 * The ComShop class is a concrete implementation of the Commercial class,
 * providing specific functionality and resources related to a shop.
 */
class ComShop : public Commercial {
public:
    /**
     * @brief Default constructor for ComShop.
     */
    ComShop();

    /**
     * @brief Destructor for ComShop.
     */
    ~ComShop();

    /**
     * @brief Displays information about the building.
     */
    void displayBuildingInfo() override;

    /**
     * @brief Gets the job capacity of the shop.
     * @return The number of jobs the shop can accommodate.
     */
    virtual int getJobCapacity() override;

    /**
     * @brief Sets the job capacity of the shop.
     * @param capacity The new job capacity to set.
     */
    virtual void setJobCapacity(int capacity) override;

    // Observer methods

    /**
     * @brief Calls utilities for the shop.
     */
    void callUtilities(); // call Utilities in Buildings

    /**
     * @brief Gets the operational state of the shop.
     * @return True if the shop is operational, false otherwise.
     */
    bool getState();

    /**
     * @brief Sets the operational state of the shop.
     * @param state The new state to set.
     */
    void setState(bool state);

    /**
     * @brief Gets the type of the building.
     * @return A string representing the building type.
     */
    string getBuildingType() override;

    /**
     * @brief Adds an employee to the shop.
     * @param employee A pointer to the Citizen representing the employee.
     * @return True if the employee was added successfully, false otherwise.
     */
    bool addEmployee(Citizen* employee);

    /**
     * @brief Removes an employee from the shop.
     * @param employee A pointer to the Citizen representing the employee.
     */
    void removeEmployee(Citizen* employee);

    /**
     * @brief Notifies that an employee has left the shop.
     * @param employee A pointer to the Citizen representing the employee.
     */
    void notifyEmployeeLeft(Citizen* employee);

    /**
     * @brief Checks if the shop has a job available.
     * @return True if there is a job available, false otherwise.
     */
    bool hasJob();

	int getElectricityUsage();
    int getWaterUsage();
    int getCurCitizenCount();

private:
    vector<Citizen*> employees; ///< List of employees in the shop.

    // Resources
    int cost = 1000;            ///< Cost of the shop.
    int jobCapacity = 10;       ///< Maximum job capacity.
    int woodCost = 5;           ///< Cost of wood for construction.
    int concreteCost = 10;      ///< Cost of concrete for construction.
    int steelCost = 5;          ///< Cost of steel for construction.
    int electricityUsage = 5;   ///< Electricity usage per time unit.
    int waterUsage = 5;         ///< Water usage per time unit.
    int income = 100;           ///< Income generated by the shop.

    string type = "Commercial Shop"; ///< Type of the building.
    bool operational;            ///< Operational state of the shop.
};

#endif // COMSHOP_H
