#ifndef SERVHOSPITAL_H
#define SERVHOSPITAL_H

#include "Services.h"

/**
 * @class ServHospital
 * @brief Represents a hospital service in the city.
 *
 * The ServHospital class manages hospital operations, employee management,
 * and visitor information, inheriting from the Services base class.
 */
class ServHospital : public Services
{
public:
    /**
     * @brief Constructs a ServHospital object.
     */
    ServHospital();

    /**
     * @brief Destroys the ServHospital object.
     */
    ~ServHospital();

    /**
     * @brief Displays information about the hospital building.
     */
    void displayBuildingInfo() override;

    /**
     * @brief Gets the number of visitors currently in the hospital.
     * @return The number of visitors.
     */
    int getVisitors() override;

    /**
     * @brief Sets the number of visitors in the hospital.
     * @param visitors The number of visitors to set.
     */
    void setVisitors(int visitors) override;

    // Observer methods

    /**
     * @brief Calls utilities in the building.
     */
    void callUtilities(); ///< Notify utilities of changes in the hospital

    /**
     * @brief Gets the operational state of the hospital.
     * @return True if the hospital is operational, false otherwise.
     */
    bool getState();

    /**
     * @brief Sets the operational state of the hospital.
     * @param state The state to set.
     */
    void setState(bool state);

    /**
     * @brief Gets the type of building.
     * @return A string representing the type of building.
     */
    std::string getBuildingType();

    // Resources management

    /**
     * @brief Adds an employee to the hospital.
     * @param employee Pointer to the Citizen to be added as an employee.
     * @return True if the employee was added successfully, false otherwise.
     */
    bool addEmployee(Citizen *employee);

    /**
     * @brief Removes an employee from the hospital.
     * @param employee Pointer to the Citizen to be removed.
     */
    void removeEmployee(Citizen *employee);

    /**
     * @brief Notifies the hospital that an employee has left.
     * @param employee Pointer to the Citizen who has left.
     */
    void notifyEmployeeLeft(Citizen *employee);

    /**
     * @brief Checks if there are job openings in the hospital.
     * @return True if there are job openings, false otherwise.
     */
    bool hasJob();

	int getElectricityUsage();
    int getWaterUsage();
    int getCurCitizenCount();

private:
    int visitors; ///< Current number of visitors in the hospital
    bool operational; ///< Operational state of the hospital
    string type = "Service Hospital"; ///< Type of service building

    // Resources
    vector<Citizen *> employees; ///< List of employees working at the hospital
    int cost = 1500; ///< Construction cost of the hospital

    int woodCost = 5; ///< Cost of wood for construction
    int steelCost = 10; ///< Cost of steel for construction
    int concreteCost = 15; ///< Cost of concrete for construction

    int electricityUsage = 10; ///< Electricity usage per unit time
    int waterUsage = 10; ///< Water usage per unit time

    int happinessIncrease = 5; ///< Increase in citizen happiness
    int jobCapacity = 20; ///< Maximum number of employees the hospital can hire
    int cityIncome = 50; ///< Income generated by the hospital
};

#endif
